# fo = open('D:\ceection.txt', 'w')
# fo.write('nishibushiwuliaole\nnihaoa')
# #fo = fo.read()
# fo.close()
# fo = open('D:\ceection.txt', 'a+')
# fod = fo.write('zheshixi\n')
# fo.close()
fo = open('D:\ceection.txt', 'r+')
fos = fo.read()
position = fo.tell()
print(position)
print(fos)
fo.close()
